### ISSUE TITLE
DevExpress License

### ISSUE THREAD

**Issue by Demotis** [sergiisyrovatchenko/SQLIndexManager#18]
DevExpress is causing issues when I try to compile.

My solution is to fork and convert to SyncFusion Community, will keep most of the features of the DevExpress controls and is Free for use.

Suggest converting the main branch to these controls.
https://www.syncfusion.com/products/communitylicense

**Comment by sergiisyrovatchenko** [comment]
Currently, I don't have any plans to migration on different UI frameworks, except DevExpress.

If you have any issues with compiling, just try to remove from license.licx file this line: _DevExpress.Patch.InMemoryPatch, DevExpress.Patch.Common, Version=6.2.0.0, Culture=neutral, PublicKeyToken=87f9927a37ac6066_

Thanks!
