### ISSUE TITLE
Feature request: Port to .Net Core/Standard (cli + business logic)

### ISSUE THREAD

**Issue by SuddenGunter** [sergiisyrovatchenko/SQLIndexManager#2]
As milestone 1 - port business logic to .Net Standard 2.0.

As milestone 2 - provide CLI tool that can work on latest LTS version .Net Core.
can be executed from local machine, or from VM based on cron.

As milestone 3 - port Windows desktop app to .Net Core 3.0 after it released.

**Comment by kiquenet** [comment]
Any good guide step-by-step for Port to .Net Core ? WPF ? Windows forms in  .Net Core 3.0  ?

**Comment by SuddenGunter** [comment]
Well, just try create new project under Net Core, copy-paste all the code, try 
`dotnet restore`
and 
`dotnet build`

I've done it several years ago while porting some stuff from .Net Fw 4.5 to .Net Core 1.0.

But I know nothing about WPF/WF so can't help with that
