### ISSUE TITLE
Tooltips to describe icons

### ISSUE THREAD

**Issue by TerriblyVexed** [sergiisyrovatchenko/SQLIndexManager#22]
Can you add tooltips at the bottom to explain the icons?

**Comment by sergiisyrovatchenko** [comment]
Hi @TerriblyVexed
You mean add more details in tooltips for all UI elements?

**Comment by TerriblyVexed** [comment]
Specifically on the bottom ribbon. The icons come up during various phases of running the UI but I don’t know what all of them mean. 
Great tool! Thank you!

**Comment by sergiisyrovatchenko** [comment]
Hi @TerriblyVexed 

Issue was fixed into master branch. Please try to use v1.0.0.68 release.

Thanks!
