### ISSUE TITLE
Version 65 runs without problems Version 66 hangs when starting

### ISSUE THREAD

**Issue by IngoManthey** [sergiisyrovatchenko/SQLIndexManager#26]
After starting the program, the login dialog is displayed. You can only see the name of the SQL server and the text of the "Save Password" checkbox. In the log directory you can only read that the layout of the grid has been restored.

**Comment by sergiisyrovatchenko** [comment]
Hi @IngoManthey. Please provide a bit more details (i.e. screenshots) about actual and expected behavior.
Thanks!

**Comment by IngoManthey** [comment]
![image](https://user-images.githubusercontent.com/30001634/116436812-27346900-a823-11eb-8b2c-fd1a11ba8882.png)

**Comment by IngoManthey** [comment]
The program show the message "No respond"
Logfile:
13:10:25.631 - Log folder: C:\Users\ingo\Downloads\SQLIndexManager
13:10:25.823 - Grid layout restored: C:\Users\ingo\Downloads\SQLIndexManager\SQLIndexManager.layout

if I remove the SQLIndexManager.layout file the program hangs too.

**Comment by sergiisyrovatchenko** [comment]
Hm....
After restart machine the same result?
Did you update your video drivers recently?
Build 65 works correctly?
Please provide windows version.

Thanks!

**Comment by IngoManthey** [comment]
After restarting the computer, it works without any problems.

Thanks for you help.

**Comment by sergiisyrovatchenko** [comment]
Have a nice day and thanks for your feedback!
