### ISSUE TITLE
Ошибка при анализе БД

### ISSUE THREAD

**Issue by Anagramma** [sergiisyrovatchenko/SQLIndexManager#28]
Запускаю приложение, выбираю БД, получаю ошибку:
![img-2021-06-18-14-00-32](https://user-images.githubusercontent.com/29057995/122562391-b142c600-d04b-11eb-93ff-d22913bebff4.png)

Нажимаю Ctrl+C
![img-2021-06-18-15-38-15](https://user-images.githubusercontent.com/29057995/122562439-bdc71e80-d04b-11eb-85dc-d52f29711d8a.png)

`See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Threading.ThreadStateException: Current thread must be set to single thread apartment (STA) mode before OLE calls can be made. Ensure that your Main function has STAThreadAttribute marked on it.
   at System.Windows.Forms.Clipboard.SetDataObject(Object data, Boolean copy, Int32 retryTimes, Int32 retryDelay)
   at DevExpress.XtraEditors.XtraMessageBoxForm.CopyContent()
   at DevExpress.XtraEditors.XtraBaseForm.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.PreProcessMessage(Message& msg)
   at System.Windows.Forms.Control.PreProcessControlMessageInternal(Control target, Message& msg)
   at System.Windows.Forms.Application.ThreadContext.PreTranslateMessage(MSG& msg)

в логе
`
15:40:05.780 - Server: SQL Server 2012 RTM (11.0.2100.60) Developer Edition (64-bit)
15:40:06.062 - Refresh databases...
15:40:06.405 - Elapsed time: 00:00:00:331. Found 5 databases
15:40:15.734 - Describe: tornado
15:40:15.796 - Error: .Net SqlClient Data Provider Недопустимое имя объекта "sys.dm_db_stats_properties".
15:40:17.499 - Processed: 0. Fragmented: 0. No indexes found. Try searching again or change settings...
`

**Comment by Anagramma** [comment]
на версии 1.0.0.65 ошибки нет

**Comment by sergiisyrovatchenko** [comment]
Hi @Anagramma 

Your error message was related to this [issue](https://www.sqlskills.com/blogs/erin/new-statistics-dmf-in-sql-server-2008r2-sp2/). I will fix it in the next build. To omit current situation you can use 65 build or update your SQL Server 2012 RTM to SP1 (or above).

Thanks for your feedback.

**Comment by Anagramma** [comment]
иду обновлять sql, спасибо.

**Comment by sergiisyrovatchenko** [comment]
Hi @Anagramma 

Issue was fixed into master branch and will be available with v1.0.0.67 release.

Thanks!
