### ISSUE TITLE
'ONLINE' is not a recognized ALTER INDEX REBUILD PARTITION option.

### ISSUE THREAD

**Issue by mchuc7719** [sergiisyrovatchenko/SQLIndexManager#31]
When try to rebuild an index over partitioned table and using the partition ID, rises the message: 'ONLINE' is not a recognized ALTER INDEX REBUILD PARTITION option.

This is the fix script:

RAISERROR(N'FDESK_CANCUN | dbo.tblUnitTime | IX_Composite_2 [ 77 ] | 6.95 MB', 0, 1) WITH NOWAIT
ALTER INDEX [IX_Composite_2] ON [dbo].[tblUnitTime] REBUILD PARTITION = 77
    WITH (SORT_IN_TEMPDB = ON, DATA_COMPRESSION = NONE, ONLINE = OFF, MAXDOP = 0);
GO

**Comment by sergiisyrovatchenko** [comment]
Hi @mchuc7719 

Please provide the version of your SQL Server instance:

`SELECT @@VERSION`

Seems you are using [SQL Server 2014 CTP1](https://sqlperformance.com/2013/09/sql-indexes/partition-index-ops-sql2014).

Thanks!

**Comment by sergiisyrovatchenko** [comment]
Hi @mchuc7719 

Re-checked current issue and I can't reproduce it at all actual versions. Please share a bit more information about your SQL Instance and provide DDL of this table.

Thanks!

**Comment by mchuc7719** [comment]
Hi Sergii,

I am using SQL Server 2012 SP4.

This is the table definition:

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[tblUnitTime](
	[pkUnitTimeID] [int] NOT NULL,
	[PropertyYear] [smallint] NOT NULL,
	[fkPropertyID] [int] NOT NULL,
	[fkPhaseID] [int] NOT NULL,
	[fkBuildingID] [int] NOT NULL,
	[fkFloorID] [int] NOT NULL,
	[fkUnitID] [int] NOT NULL,
	[fkCalendarTypeID] [int] NOT NULL,
	[dtDate] [datetime] NOT NULL,
	[DayNo] [int] NOT NULL,
	[Intv] [int] NOT NULL,
	[IntvYear] [int] NOT NULL,
	[fkInvtStatusID] [int] NOT NULL,
	[fkTitleProgTypeID] [int] NOT NULL,
	[fkTitleProgStatusID] [int] NULL,
	[ContractNo] [int] NOT NULL,
	[fkStayInfoID] [int] NULL,
	[ynAllowRRM] [bit] NULL,
	[fkUnitBlockedTypeID] [int] NULL
) ON [PScheme_Partition_PropertyYear]([PropertyYear])

GO

ALTER TABLE [dbo].[tblUnitTime] ADD  CONSTRAINT [DF_tblUnitTime_ContractNo]  DEFAULT ((0)) FOR [ContractNo]
GO

ALTER TABLE [dbo].[tblUnitTime] ADD  CONSTRAINT [DF_tblUnitTime_ynAssigned]  DEFAULT ((0)) FOR [ynAllowRRM]
GO

ALTER TABLE [dbo].[tblUnitTime]  WITH CHECK ADD  CONSTRAINT [PropertyYearRange] CHECK  (([PropertyYear]>=(105) AND [PropertyYear]<=(2534)))
GO

ALTER TABLE [dbo].[tblUnitTime] CHECK CONSTRAINT [PropertyYearRange]
GO

**Comment by mchuc7719** [comment]
Hi, Sergii,

It's me again, after review on the net, the option ONLINE is not supported in sql server 2012 for partitoned tables.

Maybe in the code you can validate the unsupported option and  do not include in the Fix Script for partitioned tables, it is just an little idea.

I am removing the ONLINE=OFF from the fix script and apply manually, your work is fully apreciated for my.

Regards.

**Comment by sergiisyrovatchenko** [comment]
Hi @mchuc7719 

Really appreciated for your information. Your situation was [fixed](https://github.com/sergiisyrovatchenko/SQLIndexManager/commit/5e1b51c8120fe4cf02fd3e416c99a6f27460b4c8) inside [1.0.0.70](https://github.com/sergiisyrovatchenko/SQLIndexManager/releases) build.

Thanks!

**Comment by mchuc7719** [comment]
Hi @sergiisyrovatchenko 

The Fix Script still showing the ONLINE option on 1.0.0.70 build:

USE [FDESK_CANCUN]
GO

RAISERROR(N'FDESK_CANCUN | dbo.tblUnitTime | IX_Composite_2 [ 117 ] | 6.20 MB', 0, 1) WITH NOWAIT
ALTER INDEX [IX_Composite_2] ON [dbo].[tblUnitTime] REBUILD PARTITION = 117
    WITH (SORT_IN_TEMPDB = ON, DATA_COMPRESSION = NONE, ONLINE = OFF, MAXDOP = 0);
GO

This is my SQL Server version:
Microsoft SQL Server 2012 (SP4-GDR) (KB4583465) - 11.0.7507.2 (X64) 
	Nov  1 2020 00:48:37 
	Copyright (c) Microsoft Corporation
	Enterprise Edition: Core-based Licensing (64-bit) on Windows NT 6.3 <X64> (Build 9600: ) (Hypervisor)

![image](https://user-images.githubusercontent.com/43049627/141871438-06979319-ed11-46a0-93ba-1ce3b5f36c48.png)

**Comment by sergiisyrovatchenko** [comment]
Hi @mchuc7719 

Sorry for the late answer - permanent tohubohu at the work 🥲

Please check a new version [v1.0.0.71](https://github.com/sergiisyrovatchenko/SQLIndexManager/releases). It's a bit strange, but I can't reproduce this issue at the same SQL Server version:

_Microsoft SQL Server 2012 (SP4-GDR) (KB4583465) - 11.0.7507.2 (X64)   Nov  1 2020 00:48:37   Copyright (c) Microsoft Corporation  Developer Edition (64-bit) on Windows NT 6.3 <X64> (Build 19042: )_ 

Thanks!

**Comment by mchuc7719** [comment]
Hi @sergiisyrovatchenko 

I just downloaded the version and the fix script not showing "online" option.

![image](https://user-images.githubusercontent.com/43049627/142731392-7504184b-9cc0-49eb-8269-f7e8be3db527.png)

I will run the index rebuild later, because our operations and users just start.

Thank you.

**Comment by sergiisyrovatchenko** [comment]
Hi @mchuc7719 

Yes. You are right. I just ignore ONLINE REBUILD for partitioned tables at SQL Server < 2014. Will wait any feedback from your side.

If your provide backup of your empty database - I will be really appreciated for this. It's will be very helpful for my testing activities in future.

Thanks!

**Comment by mchuc7719** [comment]
Hi @sergiisyrovatchenko 

The issue is not present any more.  

About the db metadata is not possible, I requested to my Supervisor the option, but was denied due a security policy, my apoligize.  

Nice and great work are you doing.  

Regards.

**Comment by sergiisyrovatchenko** [comment]
Thanks for your feedback :)
